name: Unit Tests
on: [push]
jobs:
  Unit_Tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Setup go tool chain
        uses: actions/setup-go@v5
        with:
          go-version: 1.22.2

      - name: Go version
        run: go version

      - name: Check formatting
        run: test -z $(go fmt ./...)

      - name: Unit tests
        run: go test -cover ./...
